# General configuration

Import Settings:
  Cruise Tag: EMB238
  current Dir: '.\resources\emb238_xyz_demo'
  Column Order:  ['lon','lat','depth','beam','ping']    
  Input crs: 32632
  Number of Sonar Beam: 256
  Tile Size in m: 10

Refernce Surface: 
  Filter Window Size in percentage: 20                                         # Percentage of window relative to Number of Sonar Beams
  min number of Beams required: 50

Filter Settings:
  Exclude Beam Numbers: '1:50, 206:256'                                        # beam Numner as sting e.g. '0:5, 250:512, 1000'
  Exclude Buffer ID:                                                           # '-1,-2,2,1'   Exlude Fortpint of Tiles. Small numbers starting by 1/-1 starboard and port site indicationg the outermost tiles, with increasing number toward the center. E.g (-1 removes the outermost 10 m)
  Vertical Detection Window in m: [-0.5, 0.5]                                  # clip values outside detection window, realative to mean surface
  Vertical Statistical Deviation Window: 6

Grid Settings:
  Exclude detected Outliers: True
  Grid Resolution in m: 0.25
  min number of Points per Tile required: 200
  treat Tile Overlaps: average
